project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Hello, Kevin Liu"
  site-url: https://liukang.github.io/
  favicon: images/site-logo.png
  repo-url: https://smallastream148.github.io/liukang.github.io/
  repo-actions: [edit, issue]

  page-footer: 
    left: "&copy; Copyright 2024, Chi Zhang"  

    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
#      - text: "Publications"
#        href: publications.qmd
#      - text: "Books"
#        href: books.qmd
      - text: "Blogs"
        href: blog/blog.qmd
      - text: "Codes"
        href: codes.qmd
#      - text: "中文"
#        href: Chinese.qmd
      

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细